Update codeql.yml
slightly different approach

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -71,14 +71,16 @@ jobs:
       if: matrix.language == 'c-cpp'
       run: |
         sudo apt-get -qq update
-        sudo apt-get -qq install -y libc6-dev-amd64-cross libgcc-s1-amd64-cross libtbb-dev libfl-dev ocaml camlp4 ocaml-findlib camlidl binutils-dev libiberty-dev libprotobuf-dev ocamlbuild oasis liboasis-ocaml liboasis-ocaml-dev opam erlang erlang-base libprotoc-dev ocamlweb binfmtc llvm llvm-dev clang llvm-runtime libllvm-ocaml-dev exuberant-ctags libparse-exuberantctags-perl libcamomile-ocaml-dev libgettext-ocaml libgettext-ocaml-dev z3 libz3-dev libz3-java libz3-jni libbatteries-ocaml-dev ocaml-batteries-included liblablgl-ocaml liblablgl-ocaml-dev liblablgtk2-ocaml liblablgtk2-ocaml-dev liblablgtk2-gnome-ocaml liblablgtk2-gnome-ocaml-dev liblablgtk2-gl-ocaml liblablgtk2-gl-ocaml-dev liblablgtk-extras-ocaml-dev liblablgtk3-ocaml liblablgtk3-ocaml-dev liblablgtksourceview3-ocaml liblablgtksourceview3-ocaml-dev liblablgtkspell3-ocaml liblablgtkspell3-ocaml-dev dh-make libasprintf-dev libgettextpo-dev
+        sudo apt-get -qq install -y libc6-dev-amd64-cross libgcc-s1-amd64-cross libtbb-dev libfl-dev ocaml camlp4 ocaml-findlib camlidl binutils-dev libiberty-dev libprotobuf-dev ocamlbuild oasis liboasis-ocaml liboasis-ocaml-dev opam erlang erlang-base libprotoc-dev ocamlweb binfmtc llvm llvm-dev clang llvm-runtime libllvm-ocaml-dev exuberant-ctags libparse-exuberantctags-perl libcamomile-ocaml-dev libgettext-ocaml libgettext-ocaml-dev z3 libz3-dev libz3-java libz3-jni libbatteries-ocaml-dev ocaml-batteries-included liblablgl-ocaml liblablgl-ocaml-dev liblablgtk2-ocaml liblablgtk2-ocaml-dev liblablgtk2-gnome-ocaml liblablgtk2-gnome-ocaml-dev liblablgtk2-gl-ocaml liblablgtk2-gl-ocaml-dev liblablgtk-extras-ocaml-dev liblablgtk3-ocaml liblablgtk3-ocaml-dev liblablgtksourceview3-ocaml liblablgtksourceview3-ocaml-dev liblablgtkspell3-ocaml liblablgtkspell3-ocaml-dev dh-make libasprintf-dev libgettextpo-dev libgoocanvas-2.0-dev mesa-common-dev xdot
         sudo apt-get install -y gcj-jdk || echo "will just have to do without gcj..."
         which -a opam
         opam -y init --shell-setup
         eval "$(opam env --switch=default)"
         export CHECK_IF_PREINSTALLED=false
         opam -y install xmlm ulex easy-format camomile gettext-camomile camlidl batteries lablgl lablgtk3-goocanvas2 z3 z3_tptp
-        opam -y install lablgtk3 || opam -y install lablgtk3-extras || opam -y install lablgtk3-rsvg2 || opam install -y lablgtk3-sourceview3 || opam -y install lablgtk3-gtkspell3 || opam -y install gtk-light || opam -y install lablgtk-extras || opam -y install lablgtk
+        for lablgpkg in gtk-light lablgtk lablgtk-extras lablgtk3 lablgtk3-extras lablgtk3-gtkspell3 lablgtk3-rsvg2 lablgtk3-sourceview3; do \
+          opam -y install "${lablgpkg}" || echo "unable to install ${lablgpkg}"; \
+        done
 
     # Initializes the CodeQL tools for scanning.
     - name: Initialize CodeQL
